# Generated by Django 5.2.6 on 2025-09-28 12:15

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(unique=True)),
                (
                    "short_code",
                    models.CharField(
                        default=shortener.models.generate_short_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("clicks", models.IntegerField(default=0)),
            ],
        ),
    ]
